# Generated by Django 4.0.6 on 2022-07-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRUD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.CharField(max_length=50)),
                ('typeIdUser', models.CharField(max_length=50)),
                ('namesUser', models.CharField(max_length=50)),
                ('surnamesUser', models.CharField(max_length=50)),
                ('phoneNumberUser', models.CharField(max_length=50)),
                ('landline', models.CharField(max_length=50)),
                ('emailUser', models.CharField(max_length=50)),
                ('titlePQR', models.CharField(max_length=50)),
                ('typeTiket', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('statusTiket', models.BooleanField()),
                ('dateofCreate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
